### ISSUE TITLE
Jana

### ISSUE THREAD

**Issue by felixLumyni** [felixLumyni/battlepass#1]
# 🌎 General Updates
- Added a failsafe to charged slash to make sure the charge is lost when it's used.
- Gave her projectiles mobjinfo names.
- Added exhaust for wall jumping.
- Can't wall jump while having the flag.
- Weight: 110.
- Taunts now only trigger if custom button 1 is held.

# 💨 Dash
  - Dash and dive can no longer be used outside of battle special.
  - Dash's cooldown will pause at a certain point if she remains airborne while dashing.
  - Dash tumbles if it collides with a player with 0 attack (can be parried).
  
# ⚔ Sword Attacks
  - **Dive Attack Priority:** 1/1, (2/2 stomp sweetspot).
  - **Dash Slash Priority:** 1/1, (1/2 glide sweetspot).
  - **Overhead Slash Priority:** 0/0, (1/0 glide sweetspot).
  - **Combo Slash Priority:** 0/0 (relying entirely on the hitbox to damage/block).
  - Added collision hooks to the sword's hitbox for players/projectiles.
  - Sword hitbox will not collide during the start and end of her attack animations.
  - Players with 1 defense or more can block her sword.
  - Her sword can clash with other swords.
  - Sword's hitbox during dash slash has reduced push time; it pierces defense if timed right or if the player is in a corner.
  - The effects of the sword clashing with a weak projectile are reduced during dash slash.
  - Can no longer guard/air-dodge while slashing

# ⚡ Saber Beams
 - Are now blockable (Small ones have 1atk-tumble and only damage on tumble, larger ones have 1 attack and higher blockstun)

# 🐛 Bug Fixes
- Fixed charged slash killing the game when in contact with bashables.
- Fixed a bug where she can't respawn if she died while her exhaust is up.
- Fixed some bugs involving charged slash being usable during air dodge/guard, kept one as a "feature".

# ⭐ Battle Specials

| Battle special | Cost | Cooldown | What it does |
| ------------- | ------------- | ------------- | ------------- |
| Dash | 5 rings | 2 seconds | Increase mobility for as long as Jana remains going fast |
| Dive | 10 rings | 3 seconds | An attack that scales in power the longer Jana is in the air |

# ❗  TODO (Draft):
- [ ] Non-charged slashes (maybe except the 3rd one) have severely lowered range and can clash with other projectiles
- [ ] Charging slash is a "committal move" (Can't act out of it or use other skills during it, gradually slows down Jana after charged)
- [ ] Charged saber beams have 2 atk, but leave Jana wide open for a second

**Comment by Smol6606** [comment]
https://github.com/felixLumyni/battlepatch/assets/151889205/ad16c67e-0fe3-4b0b-9ec4-f54e8704bac4

Yep, it do, its something about how the charge slash is functioned to multi hit something, and if that object
doesn't disappear, it'll keep hitting it (iirc alfredo told me), maybe hence the crash

**Comment by felixLumyni** [comment]
solved as of [commit a601a9](https://github.com/felixLumyni/battlepatch/commit/a601a9dc1e87a75dcf90b9c547df9345f8723950)

**Comment by felixLumyni** [comment]
TODO: slash rework

**Comment by felixLumyni** [comment]
(I'd also assign @JabSphere but I think he has to make a comment here)

**Comment by felixLumyni** [comment]
should be patched thanks to [Jab's MR](https://github.com/felixLumyni/battlepass/commit/6625c32151856c2799c60c91f283faddda53fa3b)
