### ISSUE TITLE
caceepass-v13.1.pk3

### ISSUE THREAD

**Issue by felixLumyni** [felixLumyni/battlepass#17]
*Branched from CL_Cacee-v2.1.1.pk3*

[DOWNLOAD v13.1](https://cdn.discordapp.com/attachments/1177410102140084334/1296325205400096848/caceepass-v13.1.pk3?ex=6711e06d&is=67108eed&hm=6d3245f649ff86224c58ded899c1f3e952643504ac69799ed9f54e6eabcdeee7&)

 ### 🌎 GENERAL:
- Changed coloration of burn and trails left by Cacee when in the blue team (punches and uppercuts)
- When triggering a guard action, shield abilities (such as the flame shield) are cancelled
- Replaced all P_TeleportMove with a safer version that prevents console warnings
Cacee is immune to other Cacee's spikey body passive (Fixes Cacee being nearly impossible to fight as another Cacee)
- Fixed elemental trails not being spawned properly when in reverse gravity in battle gametypes (probably been a thing since v1)
- Slightly increased duration of elementail trail 
- Fixed spike immunity not accounting for flagdebuff

### ✨ SPECIAL ABILITY:
- Battle special is now exclusively Pot Of Pain
- New battle special: ``Relent``
   - Available when Cacee has an active Pot Of Pain
   - By using this ability, the active Pot is manually despawned
   - Zero ring cost and applies same cooldown as waiting for the Pot to despawn

### 🌵 POT OF PAIN
- Automatically despawns when their owner dies
- Is now a cactus-like hazard (not solid, deals spike damage)
- Brighter colors (so it doesn't blend with Cacee)
- More obvious visual telegraphing on spawn (less surprise attacks)
- Fixed not awarding score to its owner on hit
- Changed thok trail to ghost/after-image trail
- Enemies that get hit by it from below (startup) are not damaged, but launched into the air
- Is pushed back by parries
- Tumbles their owner on parry if they were in contact
- Bounces away when in contact with CTF Flags and springs
- Enemy Cacee's get stunned on hit instead of being completely immune
- Can now be spawned from right under objects/players
- On spawn, has a small window of time where players get launched upwards instead of damaged (can be blocked)
- Can no longer damage players going through zoomtubes
- Matches with the player's color even after spawned
- Fixed name not showing up on console on hit

### 🥊 PUNCH:
- Can no longer punch out of slopes, springs, tumble and heavy bumps (skidtime)
- Cacee must land a hit (combo) to achieve final punch
- Second punch briefly flinches players
- Can hold down the spin button to keep punching until the combo is finished
- Can only punch twice when in the air (Restored on punch/uppercut hit)
- Fixed inconsistent powersprings
- Fixed Cacee's collision with bashables being extremely inconsistent when trying to punch them
- Power springs and boosters are triggered with 100% consistency
- Punch sweetspots can now block blockable projectiles (backported global v10 feature)
- Thrust works once again while in flagdebuff, however only if Cacee is on the ground
- Can no longer punch out of shield abilities, or use shield abilities out of a punch

### 🌪 UPPERCUT:
- Lowered all-around defense to 0
- Lower regular updraft height gain (100% -> 75%)
- Updraft only lifts players directly in front of Cacee (360° -> 40°)
- Lift angle depends on input angle
- Every player can only be lifted once, refreshes when landing
- Lower first punch minimum speed (40FRAC -> 20FRAC)
- Hitting with an uppercut prevents Cacee from being able to follow up with another, infinitely. But also re-allows punching and counts as a punch hit

# TODO for v14 - The real combo update:
- [x] Fix pot having strange interactions when being punched while spawning
- [ ] New priority and sweetspots for uppercut: 2/2 above (LENIENT), 1/1 all around except below when spinning fast, 1/0 otherwise
- [ ] Uppercut slighty adjusts horizontal momentum to catch opponents that are directly above
- [ ] New aerial ability: Lock in (TOGGLE, 1 cost, 1s cooldown on relent) - Cacee turns towards the nearest opponent in a range similar to analog mode's lock-in, but with increased strafe speed, and Cacee automatically tries to adjust her vertical position to match with the opponent's. When Cacee is locked in, she has a faint yellow outline and loses 1 ring per second, but does not wear off at 0 rings (Also, we could totally use her SOL form's sprites for this, right?)
- [ ] On aerial punches, Cacee slightly ascends/descends towards the nearest opponent if they are close and being aimed at (does NOT include horizontal homing)
- [x] When landing an aerial punch, after going into the recoil state, Cacee unlocks the 3rd punch until landing and is able to recover from the recoil with a punch after 0.5s
- [x] Final punch can be cancelled with uppercut
- [x] When spacing out aerial punches, Cacee will always increment the punch sequence instead of resetting to the first punch
- [ ] Punching opponents that are already in pain has new audio and visual effects, and they lose 5 rings on the first or second punch or 10 rings on the final punch. When the ring loss is greater than what the opponent's amount, they lose their i-frames instead. Second and final punch have an additive damage falloff of 20%, capping out at 80% until they land
- [ ] Cacee is able to punch airborne corpses
- [ ] New passive: During tumble, gains NIMBLE (Can move slightly) to prevent softlock. NIMBLE is indicated by after-images
- [ ] Opponents hit by Cacee's first punch gain NIMBLE. Second punch does not apply NIMBLE, and getting hit by final punch removes NIMBLE
- [ ] Punch UI element (Shows how many punches are available in the current combo)

**Comment by felixLumyni** [comment]
TODO: Updraft nerf

**Comment by StarHuntingNinja** [comment]
Ideas to make Cacee less insane to deal with
1). Make her updraft lift much weaker on pained players
2). Don't allow her to parry while punching
3). Since Cacee's combo punches are inconsistent and rarely used, it'd be cool if she had something like Charmy where she takes extra Knockback from bumping into others. This would make her punches less oppressive while not directly changing them. (It'd also make her updraft easier to deal with due to being able to push her away?)

4). If (1) isn't enough to tone the updraft down, it could also just lift airborne players. Idk about this change tho, but I'll leave it here as food for thought.

**Comment by StarHuntingNinja** [comment]
Oh, another suggestion is making her combo finisher have priority all around instead of a sweetspot, since it has a startup now

**Comment by lightdasher** [comment]
BM Updraft shouldn't pull up the same player if they're already been pulled up by the first upper

**Comment by lightdasher** [comment]
We probably want to lower her fast punch speed (punching while holding a direction) minimum is fine (punching without holding a direction)

Maybe lowering the cap from her momentum punch would help, too.

Oh, another thing that might help her sporatic nature, remember when Blaze Boost could essentially 180 and redirect like that? maybe trying to punch at too sharp an angle at higher speeds slows you down? Just a thought

**Comment by CyaanKnight** [comment]
You know how Beat Bash, Megaton punch and Stinger Dash kill Z momentum and force you in the direction you inputted? what if cacee's first punch was always like that? I think its what keeps a lot of dashes that would otherwise be very obnoxious in check

**Comment by felixLumyni** [comment]
- [x] fix elemental trails not spawning on punch when in reverse gravity

**Comment by felixLumyni** [comment]
Going to add some items to the TODO list. Goal: Playability and synergies to make her more fun
