### ISSUE TITLE
Flame

### ISSUE THREAD

**Issue by felixLumyni** [felixLumyni/battlepass#18]
# TODO
- [ ] ground spin doesnt curl her
- [ ] explosion radius doesnt uncurl other players
- [ ] bm ability endlag
- [ ] if the battlemove doesn't end completely, the rebound just doesn't function
