### ISSUE TITLE
Tangle

### ISSUE THREAD

**Issue by felixLumyni** [felixLumyni/battlepass#19]
**NOTE: This patch is included in Tangle's pk3 natively as a separate lua**

- Tangle gets tumbled if someone parries her tail
- Tangle's tail can interact with CTF flags
- Fixed tail giving rings to teammates

| Battle special | Cost | Cooldown | What it does |
| ------------- | ------------- | ------------- | ------------- |
| Tail Spin | 10 rings (this cost is applied to grabbed opponents instead, if there is one) | 2 seconds | Tangle starts spinning her tail around her for 1.5s, grabbing any enemy that comes in contact with it, if she is already not grabbing one. Grabbed enemies can struggle out of it as long as Tangle isn't spinning her tail. Grabbed enemies take damage and are released if Tangle's tail hits a wall. |

# TODO:
- [ ] Fix extremely inconsistent collisions involving the tail (recode the entirety of it to use mobjs and momentum instead of teleporting the tail around her)
- [ ] Fix inconsistent wall slams
- [ ] New teammate grab behavior: Holding tossflag will allow the player to be picked up by Tangle. Otherwise, Tangle can only pull herself towards the player while they remain unnafected
- [ ] When Tangle is grabbing a teammate, she gets access to 2 new specials: Bowl and Thunder Shot
