### ISSUE TITLE
MetalKnuckles

### ISSUE THREAD

**Issue by felixLumyni** [felixLumyni/battlepass#20]
I'm not sure what needs to be done for him (I don't even know if he's considered overpowered or underpowered). Please comment.

# TODO (Needs revision)
- [ ] Special ability releases less rockets (4 -> 2)
- [ ] Rocket atk increase (1 -> 2)
- [ ] Glide has lower initial speed (can still be charged for more speed)
