### ISSUE TITLE
silverhornpass-v4

### ISSUE THREAD

**Issue by felixLumyni** [felixLumyni/battlepass#22]
*Branched from B_csl_silverhornbattle-v1.4.8.pk3*

[Download](https://cdn.discordapp.com/attachments/1177410102140084334/1290512272594174035/silverhornpass-v3.pk3?ex=66fcbab6&is=66fb6936&hm=6915f2031bb736636a1f26bbc8430397eff370f668455c0bdcd4f114a0017b9f&)

# Aether

- :boom: ***Aura Burst***
  - Fixed Aura Burst console spam error
  - Aura burst can be air dodged
  - Players protected by Aura burst will still drop flags and revive jettysyns on hit
  - Added height checks to Aura burst (for tumble AoE and shield collision)
  - Aura burst no longer destroys monitors from the enemy team
  - Aura shields have 2 HP, but fade away after 3s while in 1 HP
- :crossed_swords: ***Sword Rain***
  - Sword Rain only homes in players that are tumbling
  - Removed Sword Rain floatiness when flag running
  - Slightly increased homing span area (45º -> 55º)
  - Spawned swords last 1 more second when it homes into something
  - Spawned swords also target players that just stopped tumbling
- :zap: ***Speed Wave***
  - Speed wave buff is affected by flag debuff (+%33 -> +%20)
- :cyclone: ***Arcane Rush***
  - Allies have to consent before being launched by Aether's arcane rush panels by having jump held when touching them
  - Arcane rush panels can be air dodged
- 🔆 ***Genesis***
  - While being casted, Aether suspends in the air and assumes control of the spawn points
- :gear: ***Other***
  - Can't buff other Aethers
  - Most buffs are more transparent in non-Aether players
  - Guard button is disabled during spell cast animations
  - When Aether dies, all buffs that she casted are removed from her allies. Does not remove a buff that a separate Aether gave that's still alive
  - Added "noledgegrab" to skinvars

# Inazuma
- :gear: **_General_**
  - Ensured neural shock is lost when taking damage
- :zap: **_Electric Immunity_**
  - Disabled in flagdebuff
- :zap: **_Bolt stream, Bolt blast_**
  - Can only "thok" twice
- :shield: **_Barrier_**
  - -10% exhaust on release instead of on trigger
  - Becomes transparent with exhaust
  - Plays a visual effect when exhaust reaches its limit
  - Gets pushed back when blocking projectiles
  - Improved clash physics with spindash
  - v10: While active, cannot restore air dodge
  - Disabled extra properties from most shields
  - Limits speed to 80% while in flagdebuff - also works in the air
  - Can no longer be used during bolt stream (can still be used after a bolt blast)
- :sparkler: **_Radial Flash_**
  - Allows thok afterwards
  - No longer has startup or endlag defense
  - Minimum startup time is 0.4s
  - Lowered min tumble time (1.5s -> 0.5s), but it increases depending on charge
  - v10: Debuff is only applied if the tumble was successful
  - No longer benefits from neural shock stacks
  - 2s of cooldown is always applied when the ability is cancelled, regardless if it was a natural cancel or not
  - Can no longer be used while having i-frames

# TODO for v5 (Aether):
- [ ] Aether's swords gain homing when going through her arcane pad
- [ ] Swords travel faster while Aether is in speed wave
- [ ] Swords have increased hitbox while Aether is protected by an aura shield
- [ ] When genesis is casted, all of her swords suspend in the air before exploding

# TODO for v5 (Inazuma):
- [ ] (v10) Fix interactions with ledgemeter
- [ ] Inazuma's barrier does not wear off faster when in flagdebuff

**Comment by felixLumyni** [comment]
deprecated, use silverhorntweaks from reverbal's server

**Comment by felixLumyni** [comment]
list of changes provided by ina (i edited it a bit)

**Comment by felixLumyni** [comment]
we need to buff these guys...
